//#region Imports
import { db } from "./pool"
//#endregion

//#region Type Defs
// No email field. The address is never needed to identify a user in the app —
// login looks up by blind index, and nothing in the UI displays it — so the
// public shape simply does not carry it. The encrypted copy stays in the
// database for future account recovery; see auth/emailCrypto.ts.
export type User = {
  id: string
  username: string
  color: string
}

// The public shape — never includes password_hash, and never the email columns.
// Every read below selects columns explicitly so neither can leak into an API
// response by accident.
const PUBLIC_COLUMNS = ["id", "username", "color"] as const
//#endregion

//#region Repository
export async function createUser(input: {
  // Generated by the caller (newUserId), not the database: it is the AAD that
  // binds the email ciphertext to this row, so it must exist before the insert.
  id: string
  emailIndex: string
  emailCiphertext: string
  username: string
  passwordHash: string
  color: string
}): Promise<User> {
  const row = await db
    .insertInto("users")
    .values({
      id: input.id,
      email_index: input.emailIndex,
      email_ciphertext: input.emailCiphertext,
      username: input.username,
      password_hash: input.passwordHash,
      color: input.color,
    })
    .returning(PUBLIC_COLUMNS)
    .executeTakeFirstOrThrow()
  return row
}

// Login's lookup. Takes the BLIND INDEX, never a raw address — the database has
// no column that could match a plaintext email, which is the point.
export async function findUserByEmailIndex(
  emailIndex: string,
): Promise<(User & { passwordHash: string }) | null> {
  // This is the ONE place password_hash is read, and only so login can verify
  // against it. It never leaves this function as anything but a comparison input.
  const row = await db
    .selectFrom("users")
    .select([...PUBLIC_COLUMNS, "password_hash"])
    .where("email_index", "=", emailIndex)
    .executeTakeFirst()
  if (!row) {
    return null
  }
  const { password_hash, ...user } = row
  return { ...user, passwordHash: password_hash }
}

// No production caller today — resolveSessionUser joins users to sessions in one
// query rather than looking a user up by id. Kept as the conventional finder of
// this repository (and used by the auth tests to assert what was written), so
// the next feature that needs one doesn't reinvent it.
export async function findUserById(id: string): Promise<User | null> {
  const row = await db
    .selectFrom("users")
    .select(PUBLIC_COLUMNS)
    .where("id", "=", id)
    .executeTakeFirst()
  return row ?? null
}

export async function emailIndexExists(emailIndex: string): Promise<boolean> {
  const row = await db
    .selectFrom("users")
    .select("id")
    .where("email_index", "=", emailIndex)
    .executeTakeFirst()
  return Boolean(row)
}

// Returns the stored ciphertext for a user so it can be decrypted by a caller
// that holds the key. Nothing reads this yet — it exists so the recovery path
// the encryption was chosen to preserve (password reset, email verification) is
// a feature change rather than a migration. Deliberate provisioning, same as
// rooms.title.
export async function findEmailCiphertext(
  userId: string,
): Promise<string | null> {
  const row = await db
    .selectFrom("users")
    .select("email_ciphertext")
    .where("id", "=", userId)
    .executeTakeFirst()
  return row?.email_ciphertext ?? null
}
//#endregion
