//#region Imports
import { db } from "./pool"
//#endregion

//#region Type Defs
// No email field. The address is never needed to identify a user in the app —
// login looks up by blind index, and nothing in the UI displays it — so the
// public shape simply does not carry it. The encrypted copy stays in the
// database for future account recovery; see auth/emailCrypto.ts.
//
// `emailVerified` is derived from the nullable email_verified_at timestamp (see
// toUser): the app only ever needs the boolean, never the exact time.
export type User = {
  id: string
  username: string
  color: string
  emailVerified: boolean
}

// The columns every public read selects — never password_hash, never the email
// index/ciphertext, so neither can leak into an API response by accident.
// email_verified_at is included because the public User carries its boolean
// projection; toUser collapses the timestamp to that boolean.
const PUBLIC_COLUMNS = [
  "id",
  "username",
  "color",
  "email_verified_at",
] as const

// Collapses a raw row's nullable email_verified_at timestamp into the boolean
// the User shape exposes. One place does the mapping so every finder agrees.
function toUser(row: {
  id: string
  username: string
  color: string
  email_verified_at: Date | null
}): User {
  return {
    id: row.id,
    username: row.username,
    color: row.color,
    emailVerified: row.email_verified_at !== null,
  }
}
//#endregion

//#region Repository
export async function createUser(input: {
  // Generated by the caller (newUserId), not the database: it is the AAD that
  // binds the email ciphertext to this row, so it must exist before the insert.
  id: string
  emailIndex: string
  emailCiphertext: string
  username: string
  passwordHash: string
  color: string
}): Promise<User> {
  const row = await db
    .insertInto("users")
    .values({
      id: input.id,
      email_index: input.emailIndex,
      email_ciphertext: input.emailCiphertext,
      username: input.username,
      password_hash: input.passwordHash,
      color: input.color,
    })
    .returning(PUBLIC_COLUMNS)
    .executeTakeFirstOrThrow()
  return toUser(row)
}

// Login's lookup. Takes the BLIND INDEX, never a raw address — the database has
// no column that could match a plaintext email, which is the point.
export async function findUserByEmailIndex(
  emailIndex: string,
): Promise<(User & { passwordHash: string }) | null> {
  // This is the ONE place password_hash is read, and only so login can verify
  // against it. It never leaves this function as anything but a comparison input.
  const row = await db
    .selectFrom("users")
    .select([...PUBLIC_COLUMNS, "password_hash"])
    .where("email_index", "=", emailIndex)
    .executeTakeFirst()
  if (!row) {
    return null
  }
  const { password_hash, ...rest } = row
  return { ...toUser(rest), passwordHash: password_hash }
}

// No production caller today — resolveSessionUser joins users to sessions in one
// query rather than looking a user up by id. Kept as the conventional finder of
// this repository (and used by the auth tests to assert what was written), so
// the next feature that needs one doesn't reinvent it.
export async function findUserById(id: string): Promise<User | null> {
  const row = await db
    .selectFrom("users")
    .select(PUBLIC_COLUMNS)
    .where("id", "=", id)
    .executeTakeFirst()
  return row ? toUser(row) : null
}

export async function emailIndexExists(emailIndex: string): Promise<boolean> {
  const row = await db
    .selectFrom("users")
    .select("id")
    .where("email_index", "=", emailIndex)
    .executeTakeFirst()
  return Boolean(row)
}

// Renames a user. Only the display name changes: the email index, the ciphertext
// and the password hash are untouched, so nothing about signing in is affected.
//
// The name is NOT unique in this app — two people may both be "Sam". Identity is
// the id, and every surface that shows a name pairs it with an identity colour,
// so a collision is a cosmetic overlap rather than an ambiguity.
export async function updateUsername(
  id: string,
  username: string,
): Promise<User | null> {
  const row = await db
    .updateTable("users")
    .set({ username })
    .where("id", "=", id)
    .returning(PUBLIC_COLUMNS)
    .executeTakeFirst()
  return row ? toUser(row) : null
}

// Marks an account's email as verified, stamping the moment it happened. Called
// by the verify-email route once a valid, unexpired token is redeemed. Writes
// NOW() rather than trusting a caller-supplied time, and is idempotent in effect
// — verifying an already-verified account just moves the timestamp, which the
// route avoids doing by consuming the single-use token first.
export async function updateEmailVerified(id: string): Promise<User | null> {
  const row = await db
    .updateTable("users")
    .set({ email_verified_at: new Date() })
    .where("id", "=", id)
    .returning(PUBLIC_COLUMNS)
    .executeTakeFirst()
  return row ? toUser(row) : null
}

// Replaces a user's password hash — the write behind a completed password reset.
// Only the hash changes; the email columns and verification status are untouched.
// Returns whether a row was updated so the caller can distinguish "done" from a
// user that vanished between token issue and redemption.
export async function updatePasswordHash(
  id: string,
  passwordHash: string,
): Promise<boolean> {
  const result = await db
    .updateTable("users")
    .set({ password_hash: passwordHash })
    .where("id", "=", id)
    .executeTakeFirst()
  return (result.numUpdatedRows ?? 0n) > 0n
}

// Deletes a user, and with them everything the schema hangs off their id:
// sessions, saved colours, and room memberships — including any row that made
// them an owner, so their rooms become unowned and can be claimed again.
//
// Rooms they CREATED survive, with created_by set to NULL: a room is a shared
// artefact, and closing an account should not delete other people's drawings.
// All of that is the database's own ON DELETE behaviour rather than a cascade
// re-implemented here, so it cannot drift out of step with the schema.
export async function deleteUser(id: string): Promise<boolean> {
  const result = await db
    .deleteFrom("users")
    .where("id", "=", id)
    .executeTakeFirst()
  return (result.numDeletedRows ?? 0n) > 0n
}

// Returns the stored ciphertext for a user so it can be decrypted by a caller
// that holds the key. Nothing reads this yet — it exists so the recovery path
// the encryption was chosen to preserve (password reset, email verification) is
// a feature change rather than a migration. Deliberate provisioning, same as
// rooms.title.
export async function findEmailCiphertext(
  userId: string,
): Promise<string | null> {
  const row = await db
    .selectFrom("users")
    .select("email_ciphertext")
    .where("id", "=", userId)
    .executeTakeFirst()
  return row?.email_ciphertext ?? null
}
//#endregion
